[dqp]
run_type = "plot" # "cen", "dis" or "plot"
algorithm = "rsdd" # "core" or "rsdd"
node_names = ["1", "2", "3", "4", "5", "6", "7", "8", "9"]
edge_pairs = [ # fmt: skip
    ["1", "2"],
    ["2", "3"],
    ["3", "4"],
    ["3", "6"],
    ["3", "7"],
    ["4", "5"],
    ["6", "8"],
    ["7", "9"],
]
opt_val = -60.92641675724471
data_dir = "../data/dqp/"
fig_dir = "../figures/dqp/"

[dqp.nx_options]
with_labels = true
font_size = 20
node_color = "white"
node_size = 1000
edgecolors = "black"
linewidths = 1.5
width = 1.5

[dqp.nx_options.pos]
"1" = [-2.0, 1.0]
"2" = [-1.0, 0.5]
"3" = [0.0, 0.0]
"4" = [-1.0, -0.5]
"5" = [-2.0, -1.0]
"6" = [1.0, 0.5]
"7" = [1.0, -0.5]
"8" = [2.0, 1.0]
"9" = [2.0, -1.0]

[dqp.node_params.core]
max_iter = 2000
step_size = 3.0
method = "AGM"
solver = "OSQP"
results_prefix = "../results/dqp/core"

[dqp.node_params.rsdd]
max_iter = 2000
step_size = 300.0
solver = "OSQP"
results_prefix = "../results/dqp/rsdd"
decay_rate = 0.9
penalty_factor = 1e3

[cp]
run_type = "plot" # "cen", "dis" or "plot"
node_names = [
    "1",
    "2",
    "3",
    "4",
    "5",
    "6",
    "7",
    "8",
    "9",
    "10",
    "11",
    "12",
    "13",
    "14",
    "15",
]
edge_pairs = [ # fmt: skip
    ["1", "9"],
    ["1", "11"],
    ["2", "3"],
    ["2", "6"],
    ["2", "7"],
    ["2", "10"],
    ["6", "12"],
    ["3", "15"],
    ["4", "8"],
    ["5", "14"],
    ["8", "15"],
    ["11", "13"],
    ["11", "14"],
    ["13", "15"],
]
opt_val = -62.837151677467475
data_dir = "../data/cp/"
fig_dir = "../figures/cp/"

[cp.nx_options]
with_labels = true
font_size = 20
node_color = "white"
node_size = 1000
edgecolors = "black"
linewidths = 1.5
width = 1.5

[cp.nx_options.pos]
"1" = [-3.0, 1.5]
"2" = [2.0, 1.0]
"3" = [1.0, 0.5]
"4" = [2.0, -1.0]
"5" = [-4.0, 0.0]
"6" = [1.0, 1.5]
"7" = [3.0, 0.5]
"8" = [1.0, -0.5]
"9" = [-4.0, 2.0]
"10" = [3.0, 1.5]
"11" = [-2.0, 1.0]
"12" = [0.0, 2.0]
"13" = [-1.0, 0.5]
"14" = [-3.0, 0.5]
"15" = [0.0, 0.0]

[cp.node_params]
max_iter = 3000
step_size = 10.0
method = "SM"
solver = "GLPK"
results_prefix = "../results/cp"
