# If you want to plot the graph, set GRAPH_PLOT_MODE to true
# else set it to false, the scripts will run the experiment
PLOT_MODE = true

[GRPAH_PLOT_OPTIONS]
with_labels = true
font_size = 20
node_color = "white"
node_size = 1000
edgecolors = "black"
linewidths = 1.5
width = 1.5

[DQP]
NODES = ["1", "2", "3", "4", "5", "6", "7", "8", "9"]
EDGES = [
    ["1", "2"],
    ["2", "3"],
    ["3", "4"],
    ["3", "6"],
    ["3", "7"],
    ["4", "5"],
    ["6", "8"],
    ["7", "9"]
]

[DQP.NODES_POS]
"1" = [-2.0, 1.0]
"2" = [-1.0, 0.5]
"3" = [0.0, 0.0]
"4" = [-1.0, -0.5]
"5" = [-2.0, -1.0]
"6" = [1.0, 0.5]
"7" = [1.0, -0.5]
"8" = [2.0, 1.0]
"9" = [2.0, -1.0]

[DQP.NODE_CONFIG]
iterations = 2000
step_size = 3.0
method = "AGM"
solver = "OSQP"
result_path = "../data/DQP/results"

[CP]
NODES = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15"]
EDGES = [
    ["1", "9"],
    ["1", "11"],
    ["2", "3"],
    ["2", "6"],
    ["2", "7"],
    ["2", "10"],
    ["6", "12"],
    ["3", "15"],
    ["4", "8"],
    ["5", "14"],
    ["8", "15"],
    ["11", "13"],
    ["11", "14"],
    ["13", "15"]
]

[CP.NODES_POS]
"1" =  [-3.0, 1.5 ]
"2" =  [2.0, 1.0 ]
"3" =  [1.0, 0.5 ]
"4" =  [2.0, -1.0 ]
"5" =  [-4.0, 0.0 ]
"6" =  [1.0, 1.5 ]
"7" =  [3.0, 0.5 ]
"8" =  [1.0, -0.5 ]
"9" =  [-4.0, 2.0 ]
"10" =  [3.0, 1.5 ]
"11" =  [-2.0, 1.0 ]
"12" =  [0.0, 2.0 ]
"13" =  [-1.0, 0.5 ]
"14" =  [-3.0, 0.5 ]
"15" =  [0.0, 0.0 ]

[CP.NODE_CONFIG]
iterations = 3000
step_size = 10.0
method = "SM"
solver = "GLPK"
result_path = "../data/CP/results"
