[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "gossip"
version = "0.1.0"
description = "Gossip Protocol"
authors = [
    {name = "Rui Huang", email = "R.Huang@lboro.ac.uk"}
]
