[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
requires-python = ">=3.10"
name = "drgt"
version = "0.1.0"
description = "Dual Robust Gradient Tracking."
authors = [
    {name = "Rui Huang", email = "R.Huang@lboro.ac.uk"}
]
